# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Local data ingest

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Change description'
        # Default value if no value is explicitly provided
        default: 'Default branch for PP/SIT is main and for lower env develop'
        # Input has to be provided for the workflow to run
        required: true
        
#on:
 # push:
  #  branches: [ main ]
  #pull_request:
   # branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn spring-boot:run -Dspring-boot.run.profiles=local

