# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Cloud Data Ingestion Workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Change description'
        # Default value if no value is explicitly provided
        #default: 'Default branch for PP/SIT is main and for lower env develop'
        # Input has to be provided for the workflow to run
        required: true
      env:
        description: "Data Ingestion Environment(DEV/SIT/PP/PROD)"        
        required: true
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'

    #on:
 # push:
  #  branches: [ main ]
  #pull_request:
   # branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    
    environment:
      name: ${{github.event.inputs.env}}
      

    steps:    
    - name: check lower environmnet
      if: ${{github.event.inputs.env == 'DEV'}}
      run: echo Valid branch
    - name : Git checkout
      uses: actions/checkout@v2
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn spring-boot:run -Dspring-boot.run.profiles=${{github.event.inputs.env}}

